name: Docker Publish

on:
  push:
    tags:
      - 'v*'  # Dispara el workflow para cualquier tag que comience con 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Tu nombre de usuario de Docker Hub
          password: ${{ secrets.DOCKER_HUB_TOKEN }}      # Tu token de acceso de Docker Hub

      - name: Build the Docker image
        run: |
          
          docker build -t aaleex/mi-imagen:${{ github.ref }} .

      - name: Push the Docker image
        run: |
          
          docker push aaleex/mi-imagen:${{ github.ref }}
